-- Auto-generated by pipeline/gen_od_slippage.py. DO NOT hand-edit; regenerate.
-- =============================================================================
-- OD SLIPPAGE / Previous Slippage (12M)
--   Population : current OD-slippage loans — Regular at m0 (previous month-end)
--                AND currently OD (live dpd>0) = the OD Status matrix "OD Slippage".
--   Metric     : prev_slippage_count = # of 0->OD slippage events in the trailing
--                12 completed months (m0..m11) — how many times it slipped before.
--   Method     : month-end OD recomputed from repayment history, 14 snapshots
--                (m0..m13). Bounded to currently-OD loans (live dpd>0) to stay light.
--   NOTE       : recompute-based approximation (warehouse lacks 12M recorded
--                monthly buckets); improves once rpt_dpd_snapshot accrues real months.
-- =============================================================================
WITH
-- Write-off master matched on loan_id AND date (loan_id repeats across JLG/IL;
-- a write-off can only apply to a loan that existed when it was written off).
wo_master AS (
    SELECT v.loan_id::bigint AS loan_id, v.wo_date::date AS wo_date
    FROM (VALUES {wo_pairs}) AS v(loan_id, wo_date)
),
hierarchy AS (
    SELECT bm.branch_id, bm.branch_name, a.area_name,
        reg.branch_name AS region_name, clus.area_name AS cluster_name,
        z.area_name AS zone_name, bm.state_id, bm.district_id
    FROM public.brnch_master bm
    LEFT JOIN public.area_master  a    ON bm.area_id   = a.area_id
    LEFT JOIN public.brnch_master reg  ON bm.region_id = reg.branch_id
    LEFT JOIN public.area_master  clus ON reg.area_id  = clus.area_id
    LEFT JOIN public.area_master  z    ON clus.zone_id = z.area_id
    WHERE bm.active='Y' AND bm.is_region='N' AND bm.branch_name<>'DEMO' AND bm.closing_date IS NULL
),

-- ── IL currently-OD candidates ───────────────────────────────────────────────
il_cand AS (
    SELECT la.loan_id, la.branch_id,
        la.loan_officer::varchar AS lo_id,
        CASE WHEN upper(trim(la.product_id::text)) LIKE '%SUGAM%'
              OR upper(trim(la.product_id::text)) LIKE '%UDYOGINI%'
              OR upper(trim(la.product_id::text)) LIKE '%SECURED%' THEN 'LAP' ELSE 'IEL' END AS business_segment,
        la.principal_outstanding AS pos,
        CASE WHEN la.status='W' OR (w.loan_id IS NOT NULL
                 AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date))
             THEN 'W' ELSE la.status END AS raw_status
    FROM public.loan_account_il la
    LEFT JOIN wo_master w ON w.loan_id = la.loan_id
    WHERE la.status IN ('A','D','I','W') AND coalesce(la.dpd,0) > 0
      -- Universe aligned with aum_status so this report equals the OD Status
      -- matrix "OD Slippage" column exactly (was over-counting: current-month
      -- disbursals cannot have slipped from a month-end they did not exist at).
      AND la.loan_id >= 10000000
      AND la.disbursement_date::date <= (date_trunc('month', current_date) - interval '1 day')::date
      AND (la.closure_date IS NULL OR la.closure_date::date > current_date - 1 OR la.status = 'W')
      -- Excl. W/O basis: this report must equal the OD Status matrix "OD Slippage"
      -- column (and the Excel OD Slippage sheet), both of which drop write-offs.
      -- Uses the write-off MASTER, not just core status='W'.
      AND NOT (la.status = 'W' OR (w.loan_id IS NOT NULL
               AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date)))
),
il_due AS (
    SELECT rs.loan_id,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>0) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_0,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>1) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_1,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>2) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_2,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>3) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_3,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>4) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_4,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>5) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_5,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>6) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_6,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>7) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_7,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>8) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_8,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>9) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_9,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>10) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_10,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>11) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_11,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>12) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_12,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>13) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_13
    FROM public.repayment_schedule_il rs
    JOIN il_cand c ON c.loan_id = rs.loan_id
    GROUP BY rs.loan_id
),
il_coll AS (
    SELECT rd.loan_id,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>0) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_0,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>1) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_1,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>2) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_2,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>3) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_3,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>4) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_4,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>5) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_5,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>6) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_6,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>7) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_7,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>8) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_8,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>9) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_9,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>10) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_10,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>11) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_11,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>12) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_12,
        sum(CASE WHEN rd.collection_date_time::date <= (date_trunc('month', current_date) - make_interval(months=>13) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_13
    FROM public.repayment_detail_il rd
    JOIN il_cand c ON c.loan_id = rd.loan_id
    WHERE rd.status IN ('A','V')
    GROUP BY rd.loan_id
),
il_od AS (
    SELECT 'IL'::text AS loan_source, c.loan_id, c.branch_id, c.lo_id, c.business_segment, c.pos, c.raw_status,
        (coalesce(d.due_0,0) > coalesce(cx.coll_0,0))::int AS od_0,
        (coalesce(d.due_1,0) > coalesce(cx.coll_1,0))::int AS od_1,
        (coalesce(d.due_2,0) > coalesce(cx.coll_2,0))::int AS od_2,
        (coalesce(d.due_3,0) > coalesce(cx.coll_3,0))::int AS od_3,
        (coalesce(d.due_4,0) > coalesce(cx.coll_4,0))::int AS od_4,
        (coalesce(d.due_5,0) > coalesce(cx.coll_5,0))::int AS od_5,
        (coalesce(d.due_6,0) > coalesce(cx.coll_6,0))::int AS od_6,
        (coalesce(d.due_7,0) > coalesce(cx.coll_7,0))::int AS od_7,
        (coalesce(d.due_8,0) > coalesce(cx.coll_8,0))::int AS od_8,
        (coalesce(d.due_9,0) > coalesce(cx.coll_9,0))::int AS od_9,
        (coalesce(d.due_10,0) > coalesce(cx.coll_10,0))::int AS od_10,
        (coalesce(d.due_11,0) > coalesce(cx.coll_11,0))::int AS od_11,
        (coalesce(d.due_12,0) > coalesce(cx.coll_12,0))::int AS od_12,
        (coalesce(d.due_13,0) > coalesce(cx.coll_13,0))::int AS od_13
    FROM il_cand c
    LEFT JOIN il_due  d  ON d.loan_id  = c.loan_id
    LEFT JOIN il_coll cx ON cx.loan_id = c.loan_id
),

-- ── JLG currently-OD candidates ──────────────────────────────────────────────
jlg_cand AS (
    SELECT la.loan_id, cm.branch_id, cm.assigned_to::varchar AS lo_id, 'JLG'::text AS business_segment,
        la.prin_os AS pos,
        CASE WHEN la.status='W' OR (w.loan_id IS NOT NULL
                 AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date))
             THEN 'W' ELSE la.status END AS raw_status
    FROM public.home_loan_account la
    JOIN public.home_center_master cm ON cm.center_id = la.center_id
    LEFT JOIN wo_master w ON w.loan_id = la.loan_id
    WHERE la.status IN ('A','D','I','W') AND coalesce(la.dpd,0) > 0
      AND (la.status <> 'W' OR la.prin_os > 0)
      -- Universe aligned with aum_status (see il_base above).
      AND la.loan_id >= 10000000
      AND la.disbursement_date::date <= (date_trunc('month', current_date) - interval '1 day')::date
      AND (la.closure_date IS NULL OR la.closure_date::date > current_date - 1 OR la.status = 'W')
      -- Excl. W/O basis: this report must equal the OD Status matrix "OD Slippage"
      -- column (and the Excel OD Slippage sheet), both of which drop write-offs.
      -- Uses the write-off MASTER, not just core status='W'.
      AND NOT (la.status = 'W' OR (w.loan_id IS NOT NULL
               AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date)))
      AND NOT EXISTS (
          SELECT 1 FROM public.loan_account_il il
          WHERE il.loan_id = la.loan_id AND il.status IN ('A','D','I','W')
            AND il.disbursement_date > la.disbursement_date)
),
jlg_due AS (
    SELECT rs.loan_id,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>0) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_0,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>1) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_1,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>2) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_2,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>3) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_3,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>4) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_4,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>5) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_5,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>6) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_6,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>7) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_7,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>8) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_8,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>9) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_9,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>10) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_10,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>11) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_11,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>12) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_12,
        max(CASE WHEN rs.demand_date::date <= (date_trunc('month', current_date) - make_interval(months=>13) - interval '1 day')::date THEN rs.cumulative_principal_due + rs.cumulative_interest_due END) AS due_13
    FROM public.repayment_schedule rs
    JOIN jlg_cand c ON c.loan_id = rs.loan_id
    GROUP BY rs.loan_id
),
jlg_coll AS (
    SELECT rd.loan_id,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>0) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_0,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>1) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_1,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>2) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_2,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>3) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_3,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>4) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_4,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>5) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_5,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>6) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_6,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>7) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_7,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>8) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_8,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>9) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_9,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>10) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_10,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>11) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_11,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>12) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_12,
        sum(CASE WHEN rd.collection_date::date <= (date_trunc('month', current_date) - make_interval(months=>13) - interval '1 day')::date THEN coalesce(rd.principal_collected,0)+coalesce(rd.interest_collected,0) ELSE 0 END) AS coll_13
    FROM public.repayment_detail rd
    JOIN jlg_cand c ON c.loan_id = rd.loan_id
    WHERE rd.status IN ('A','V')
    GROUP BY rd.loan_id
),
jlg_od AS (
    SELECT 'JLG'::text AS loan_source, c.loan_id, c.branch_id, c.lo_id, c.business_segment, c.pos, c.raw_status,
        (coalesce(d.due_0,0) > coalesce(cx.coll_0,0))::int AS od_0,
        (coalesce(d.due_1,0) > coalesce(cx.coll_1,0))::int AS od_1,
        (coalesce(d.due_2,0) > coalesce(cx.coll_2,0))::int AS od_2,
        (coalesce(d.due_3,0) > coalesce(cx.coll_3,0))::int AS od_3,
        (coalesce(d.due_4,0) > coalesce(cx.coll_4,0))::int AS od_4,
        (coalesce(d.due_5,0) > coalesce(cx.coll_5,0))::int AS od_5,
        (coalesce(d.due_6,0) > coalesce(cx.coll_6,0))::int AS od_6,
        (coalesce(d.due_7,0) > coalesce(cx.coll_7,0))::int AS od_7,
        (coalesce(d.due_8,0) > coalesce(cx.coll_8,0))::int AS od_8,
        (coalesce(d.due_9,0) > coalesce(cx.coll_9,0))::int AS od_9,
        (coalesce(d.due_10,0) > coalesce(cx.coll_10,0))::int AS od_10,
        (coalesce(d.due_11,0) > coalesce(cx.coll_11,0))::int AS od_11,
        (coalesce(d.due_12,0) > coalesce(cx.coll_12,0))::int AS od_12,
        (coalesce(d.due_13,0) > coalesce(cx.coll_13,0))::int AS od_13
    FROM jlg_cand c
    LEFT JOIN jlg_due  d  ON d.loan_id  = c.loan_id
    LEFT JOIN jlg_coll cx ON cx.loan_id = c.loan_id
),

all_od AS (
    SELECT * FROM il_od
    UNION ALL
    SELECT * FROM jlg_od
),

computed AS (
    SELECT loan_source, loan_id, branch_id, lo_id, business_segment, pos, raw_status,
        (od_0 = 0) AS current_slip,  -- Regular at prev month-end (m0) & currently OD (dpd>0 bound) = OD Slippage per matrix DAX
        (
            (CASE WHEN od_0=1 AND od_1=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_1=1 AND od_2=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_2=1 AND od_3=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_3=1 AND od_4=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_4=1 AND od_5=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_5=1 AND od_6=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_6=1 AND od_7=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_7=1 AND od_8=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_8=1 AND od_9=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_9=1 AND od_10=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_10=1 AND od_11=0 THEN 1 ELSE 0 END) +
            (CASE WHEN od_11=1 AND od_12=0 THEN 1 ELSE 0 END)
        ) AS prev_slippage_count
    FROM all_od
)

SELECT
    c.business_segment,
    coalesce(h.zone_name,    'Unassigned') AS zone_name,
    coalesce(h.cluster_name, 'Unassigned') AS cluster_name,
    coalesce(h.region_name,  'Unassigned') AS region_name,
    coalesce(h.area_name,    'Unassigned') AS area_name,
    coalesce(h.branch_name,  'Unassigned') AS branch_name,
    c.branch_id,
    coalesce(c.lo_id, 'N/A')               AS lo_id,
    coalesce(h.state_id::text,    'N/A')   AS state_id,
    coalesce(h.district_id::text, 'N/A')   AS district_id,
    c.loan_id,
    CASE c.raw_status WHEN 'A' THEN 'Active' WHEN 'D' THEN 'Death' WHEN 'I' THEN 'Death'
         WHEN 'W' THEN 'Write-off' ELSE c.raw_status END AS loan_status,
    c.prev_slippage_count,
    round(c.pos::numeric, 2)               AS pos
FROM computed c
LEFT JOIN hierarchy h ON c.branch_id = h.branch_id
WHERE c.current_slip
ORDER BY c.prev_slippage_count DESC, c.pos DESC;
