"""Generator for queries/od_slippage.sql — OD Slippage / Previous Slippage (12M).

14 month-end OD snapshots (m0..m13) recomputed from repayment history, bounded to
currently-OD loans (live dpd>0) so the replica scan stays light. Yields, per current
OD-slippage loan, the count of prior 0->OD slippage events in the trailing 12 months.
Run:  python -m pipeline.gen_od_slippage   (rewrites queries/od_slippage.sql)
"""
import os

N = 14  # snapshots m0 (last completed month-end) .. m13


def me(i):
    # Month-end reference = the LAST COMPLETED month-end (NBFC standard), matching
    # aum_status.sql's ref CTE and trend_full. NOT the T-1 form, which on the 1st of
    # a month resolves one month further back. Identical on every other day.
    return f"(date_trunc('month', current_date) - make_interval(months=>{i}) - interval '1 day')::date"


def due_cols(rs):
    return ",\n        ".join(
        f"max(CASE WHEN {rs}.demand_date::date <= {me(i)} "
        f"THEN {rs}.cumulative_principal_due + {rs}.cumulative_interest_due END) AS due_{i}"
        for i in range(N))


def coll_cols(rd, dtcol):
    return ",\n        ".join(
        f"sum(CASE WHEN {rd}.{dtcol}::date <= {me(i)} "
        f"THEN coalesce({rd}.principal_collected,0)+coalesce({rd}.interest_collected,0) ELSE 0 END) AS coll_{i}"
        for i in range(N))


OD_FLAGS = ",\n        ".join(
    f"(coalesce(d.due_{i},0) > coalesce(cx.coll_{i},0))::int AS od_{i}" for i in range(N))

# previous slippages = 0->OD transitions in the trailing 12 completed months
# (a slip "into month ending m_i" = OD at m_i AND regular at m_{i+1}), i = 0..11.
# Current slippers are regular at m0 (so the m0 term is 0); this counts prior slips.
PREV = " +\n            ".join(
    f"(CASE WHEN od_{i}=1 AND od_{i+1}=0 THEN 1 ELSE 0 END)" for i in range(0, 12))


def od_cte(name, source, cand):
    return f"""{name} AS (
    SELECT '{source}'::text AS loan_source, c.loan_id, c.branch_id, c.lo_id, c.business_segment, c.pos, c.raw_status,
        {OD_FLAGS}
    FROM {cand} c
    LEFT JOIN {cand.replace('_cand', '_due')}  d  ON d.loan_id  = c.loan_id
    LEFT JOIN {cand.replace('_cand', '_coll')} cx ON cx.loan_id = c.loan_id
)"""


SQL = f"""-- Auto-generated by pipeline/gen_od_slippage.py. DO NOT hand-edit; regenerate.
-- =============================================================================
-- OD SLIPPAGE / Previous Slippage (12M)
--   Population : current OD-slippage loans — Regular at m0 (previous month-end)
--                AND currently OD (live dpd>0) = the OD Status matrix "OD Slippage".
--   Metric     : prev_slippage_count = # of 0->OD slippage events in the trailing
--                12 completed months (m0..m11) — how many times it slipped before.
--   Method     : month-end OD recomputed from repayment history, 14 snapshots
--                (m0..m13). Bounded to currently-OD loans (live dpd>0) to stay light.
--   NOTE       : recompute-based approximation (warehouse lacks 12M recorded
--                monthly buckets); improves once rpt_dpd_snapshot accrues real months.
-- =============================================================================
WITH
-- Write-off master matched on loan_id AND date (loan_id repeats across JLG/IL;
-- a write-off can only apply to a loan that existed when it was written off).
wo_master AS (
    SELECT v.loan_id::bigint AS loan_id, v.wo_date::date AS wo_date
    FROM (VALUES {{wo_pairs}}) AS v(loan_id, wo_date)
),
hierarchy AS (
    SELECT bm.branch_id, bm.branch_name, a.area_name,
        reg.branch_name AS region_name, clus.area_name AS cluster_name,
        z.area_name AS zone_name, bm.state_id, bm.district_id
    FROM public.brnch_master bm
    LEFT JOIN public.area_master  a    ON bm.area_id   = a.area_id
    LEFT JOIN public.brnch_master reg  ON bm.region_id = reg.branch_id
    LEFT JOIN public.area_master  clus ON reg.area_id  = clus.area_id
    LEFT JOIN public.area_master  z    ON clus.zone_id = z.area_id
    WHERE bm.active='Y' AND bm.is_region='N' AND bm.branch_name<>'DEMO' AND bm.closing_date IS NULL
),

-- ── IL currently-OD candidates ───────────────────────────────────────────────
il_cand AS (
    SELECT la.loan_id, la.branch_id,
        la.loan_officer::varchar AS lo_id,
        CASE WHEN upper(trim(la.product_id::text)) LIKE '%SUGAM%'
              OR upper(trim(la.product_id::text)) LIKE '%UDYOGINI%'
              OR upper(trim(la.product_id::text)) LIKE '%SECURED%' THEN 'LAP' ELSE 'IEL' END AS business_segment,
        la.principal_outstanding AS pos,
        CASE WHEN la.status='W' OR (w.loan_id IS NOT NULL
                 AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date))
             THEN 'W' ELSE la.status END AS raw_status
    FROM public.loan_account_il la
    LEFT JOIN wo_master w ON w.loan_id = la.loan_id
    WHERE la.status IN ('A','D','I','W') AND coalesce(la.dpd,0) > 0
      -- Universe aligned with aum_status so this report equals the OD Status
      -- matrix "OD Slippage" column exactly (was over-counting: current-month
      -- disbursals cannot have slipped from a month-end they did not exist at).
      AND la.loan_id >= 10000000
      AND la.disbursement_date::date <= (date_trunc('month', current_date) - interval '1 day')::date
      AND (
           -- LIVE book, open as of T-1.
           (la.closure_date IS NULL OR la.closure_date::date > current_date - 1 OR la.status = 'W')
        OR
           -- MOVEMENT arm: on-book at prev month-end, closed during the current
           -- month. aum_status gained this arm so OD Status / Bucket Movement
           -- reconcile to the M-1 portfolio; this query kept only the live arm
           -- and so drifted one loan below the matrix it claims to equal.
           -- Its assumption that closures "carry POS=0, live DPD=0" does not
           -- always hold: IL 10015044 is a status='I' death case closed on
           -- 2026-08-20 still carrying POS 21,921 and arrears 5,490 at DPD 16.
           -- It slipped from Regular at 31-Jul and rpt_collection_loans flags it
           -- ftod_flag=1, so every other report counts it. Dropping it here is
           -- what made this page read 2,023 against 2,024 everywhere else.
           (la.closure_date::date >  (date_trunc('month', current_date) - interval '1 day')::date
            AND la.closure_date::date <= current_date - 1)
      )
      -- Write-offs are NO LONGER excluded here. They are emitted with
      -- in_od_matrix = FALSE instead, so this table is the single source for
      -- both "every loan that slipped" and "the OD Status matrix column".
      -- EVERY consumer must filter in_od_matrix IS TRUE to keep matching the
      -- matrix and the Excel OD Slippage sheet, which both drop write-offs.
),
il_due AS (
    SELECT rs.loan_id,
        {due_cols('rs')}
    FROM public.repayment_schedule_il rs
    JOIN il_cand c ON c.loan_id = rs.loan_id
    GROUP BY rs.loan_id
),
il_coll AS (
    SELECT rd.loan_id,
        {coll_cols('rd', 'collection_date_time')}
    FROM public.repayment_detail_il rd
    JOIN il_cand c ON c.loan_id = rd.loan_id
    WHERE rd.status IN ('A','V')
    GROUP BY rd.loan_id
),
{od_cte('il_od', 'IL', 'il_cand')},

-- ── JLG currently-OD candidates ──────────────────────────────────────────────
jlg_cand AS (
    SELECT la.loan_id, cm.branch_id, cm.assigned_to::varchar AS lo_id, 'JLG'::text AS business_segment,
        la.prin_os AS pos,
        CASE WHEN la.status='W' OR (w.loan_id IS NOT NULL
                 AND (w.wo_date IS NULL OR la.disbursement_date::date <= w.wo_date))
             THEN 'W' ELSE la.status END AS raw_status
    FROM public.home_loan_account la
    JOIN public.home_center_master cm ON cm.center_id = la.center_id
    LEFT JOIN wo_master w ON w.loan_id = la.loan_id
    WHERE la.status IN ('A','D','I','W') AND coalesce(la.dpd,0) > 0
      AND (la.status <> 'W' OR la.prin_os > 0)
      -- Universe aligned with aum_status (see il_base above) — INCLUDING the
      -- current-month closure arm, so this page equals the OD Status matrix.
      AND la.loan_id >= 10000000
      AND la.disbursement_date::date <= (date_trunc('month', current_date) - interval '1 day')::date
      AND (
           (la.closure_date IS NULL OR la.closure_date::date > current_date - 1 OR la.status = 'W')
        OR (la.closure_date::date >  (date_trunc('month', current_date) - interval '1 day')::date
            AND la.closure_date::date <= current_date - 1)
      )
      -- Write-offs are NO LONGER excluded here. They are emitted with
      -- in_od_matrix = FALSE instead, so this table is the single source for
      -- both "every loan that slipped" and "the OD Status matrix column".
      -- EVERY consumer must filter in_od_matrix IS TRUE to keep matching the
      -- matrix and the Excel OD Slippage sheet, which both drop write-offs.
      AND NOT EXISTS (
          SELECT 1 FROM public.loan_account_il il
          WHERE il.loan_id = la.loan_id AND il.status IN ('A','D','I','W')
            AND il.disbursement_date > la.disbursement_date)
),
jlg_due AS (
    SELECT rs.loan_id,
        {due_cols('rs')}
    FROM public.repayment_schedule rs
    JOIN jlg_cand c ON c.loan_id = rs.loan_id
    GROUP BY rs.loan_id
),
jlg_coll AS (
    SELECT rd.loan_id,
        {coll_cols('rd', 'collection_date')}
    FROM public.repayment_detail rd
    JOIN jlg_cand c ON c.loan_id = rd.loan_id
    WHERE rd.status IN ('A','V')
    GROUP BY rd.loan_id
),
{od_cte('jlg_od', 'JLG', 'jlg_cand')},

all_od AS (
    SELECT * FROM il_od
    UNION ALL
    SELECT * FROM jlg_od
),

computed AS (
    SELECT loan_source, loan_id, branch_id, lo_id, business_segment, pos, raw_status,
        (od_0 = 0) AS current_slip,  -- Regular at prev month-end (m0) & currently OD (dpd>0 bound) = OD Slippage per matrix DAX
        (
            {PREV}
        ) AS prev_slippage_count
    FROM all_od
)

SELECT
    c.business_segment,
    coalesce(h.zone_name,    'Unassigned') AS zone_name,
    coalesce(h.cluster_name, 'Unassigned') AS cluster_name,
    coalesce(h.region_name,  'Unassigned') AS region_name,
    coalesce(h.area_name,    'Unassigned') AS area_name,
    coalesce(h.branch_name,  'Unassigned') AS branch_name,
    c.branch_id,
    coalesce(c.lo_id, 'N/A')               AS lo_id,
    coalesce(h.state_id::text,    'N/A')   AS state_id,
    coalesce(h.district_id::text, 'N/A')   AS district_id,
    c.loan_id,
    CASE c.raw_status WHEN 'A' THEN 'Active' WHEN 'D' THEN 'Death' WHEN 'I' THEN 'Death'
         WHEN 'W' THEN 'Write-off' ELSE c.raw_status END AS loan_status,
    -- TRUE = counts toward the OD Status matrix "OD Slippage" column and the
    -- Excel sheet (both drop write-offs). FALSE = slipped this month but has
    -- since been written off; carried so the page can show the total and the
    -- excluded split from ONE source instead of reading a second table.
    (c.raw_status <> 'W')                            AS in_od_matrix,
    c.prev_slippage_count,
    round(c.pos::numeric, 2)               AS pos
FROM computed c
LEFT JOIN hierarchy h ON c.branch_id = h.branch_id
WHERE c.current_slip
ORDER BY c.prev_slippage_count DESC, c.pos DESC;
"""

out = os.path.join(os.path.dirname(__file__), "queries", "od_slippage.sql")
with open(out, "w", encoding="utf-8") as f:
    f.write(SQL)
print("wrote", out, len(SQL), "chars")
