"""Write ready-to-run trend SQL for manual pgAdmin validation on the SOURCE replica.

The pipeline's trend_full_il.sql / trend_full_jlg.sql carry placeholders
({wo_pairs}, {wo_ids}, {chunk_pred}) and cannot be pasted into pgAdmin as-is.
More importantly, the JLG file run WHOLE is a ~2-minute query the replica cancels
under load ("SSL connection has been closed unexpectedly"). This script writes
fully-substituted copies into pipeline/queries/manual/:

    manual_trend_full_il.sql            — IL, whole book (~6s)
    manual_trend_full_jlg_chunk0.sql    — JLG, loan_id chunk 0 of N (~22s)
    ... one per chunk ...
    manual_trend_full_jlg_ALL.sql       — all N chunks UNIONed into a #-grain
                                          rollup via a TEMP table (run top-to-bottom)

Each chunk file is safe to run in pgAdmin against the SOURCE replica
(ananyaapp-replica…, db Ananya_app_prod). To reproduce a dashboard figure for a
month, run the chunks and SUM them — the dashboard's rpt_trend_full is exactly
the re-aggregated union of these chunks (plus IL).

Run:  python -m pipeline.materialize_trend_sql          (default N = TREND_JLG_CHUNKS or 6)
"""
import os

from pipeline.load_writeoff_master import get_writeoff_ids, writeoff_values_literal

BASE = os.path.dirname(os.path.abspath(__file__))
QDIR = os.path.join(BASE, "queries")
OUT = os.path.join(QDIR, "manual")
N = int(os.getenv("TREND_JLG_CHUNKS", "6"))

HEADER = (
    "-- AUTO-GENERATED by pipeline/materialize_trend_sql.py — DO NOT hand-edit.\n"
    "-- Run in pgAdmin against the SOURCE replica (Ananya_app_prod).\n"
    "-- Write-off master baked in as of generation time; regenerate after a refresh.\n\n"
)


def _fill(fname, chunk_pred):
    sql = open(os.path.join(QDIR, fname), encoding="utf-8").read()
    ids = ",".join(str(i) for i in get_writeoff_ids()) or "0"
    return (sql.replace("{wo_pairs}", writeoff_values_literal())
               .replace("{wo_ids}", ids)
               .replace("{chunk_pred}", chunk_pred))


def main():
    os.makedirs(OUT, exist_ok=True)

    # IL — whole book
    with open(os.path.join(OUT, "manual_trend_full_il.sql"), "w", encoding="utf-8") as f:
        f.write(HEADER + _fill("trend_full_il.sql", ""))

    # JLG — one file per loan_id chunk
    for k in range(N):
        pred = f"AND mod(la.loan_id, {N}) = {k}"
        with open(os.path.join(OUT, f"manual_trend_full_jlg_chunk{k}.sql"),
                  "w", encoding="utf-8") as f:
            f.write(HEADER + f"-- JLG loan_id chunk {k} of {N}: {pred}\n\n"
                    + _fill("trend_full_jlg.sql", pred))

    print(f"Wrote IL + {N} JLG chunk files to {OUT}")
    print("Paste any one into pgAdmin (SOURCE replica). Each JLG chunk ~22s;")
    print("sum the N chunks to get a whole-JLG month total.")


if __name__ == "__main__":
    main()
