"""Write a ready-to-run, loan-grain Current Outstanding validation query for pgAdmin.

validation_loans_aum.sql carries a {wo_pairs} placeholder (the write-off master
lives in the report DB, unreachable from the source replica, so it is baked in as
a literal). This writes the filled version to pipeline/queries/manual/:

    manual_validation_loans_aum.sql   — one row per loan in the Current Outstanding
                                        universe (~3.5s on the source replica)

Use it to diff our loan set against the loandump / Excel:
  * segment totals:  GROUP BY business_segment  (Excl W/O = WHERE loan_status<>'Write-off')
  * loan-level diff: export loan_id list, compare to the loandump's loan_id list.

Run:  python -m pipeline.materialize_validation_sql   (regenerate after a write-off refresh)
"""
import os

from pipeline.load_writeoff_master import writeoff_values_literal

BASE = os.path.dirname(os.path.abspath(__file__))
QDIR = os.path.join(BASE, "queries")
OUT = os.path.join(QDIR, "manual")

HEADER = (
    "-- AUTO-GENERATED by pipeline/materialize_validation_sql.py — DO NOT hand-edit.\n"
    "-- Run in pgAdmin against the SOURCE replica (Ananya_app_prod).\n"
    "-- Write-off master baked in as of generation time; regenerate after a refresh.\n\n"
)


def main():
    os.makedirs(OUT, exist_ok=True)
    sql = open(os.path.join(QDIR, "validation_loans_aum.sql"), encoding="utf-8").read()
    sql = sql.replace("{wo_pairs}", writeoff_values_literal())
    dst = os.path.join(OUT, "manual_validation_loans_aum.sql")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(HEADER + sql)
    print(f"Wrote {dst}")
    print("Paste into pgAdmin (SOURCE replica). ~3.5s, one row per loan.")


if __name__ == "__main__":
    main()
