#!/usr/bin/env bash
# =============================================================================
# install-pipeline-timer.sh — put the MIS daily pipeline on a Linux server.
#
# Replaces the Windows Task Scheduler job on the laptop, which could not work
# unattended: LogonType=Interactive (no logged-in session, no run), WakeToRun
# false (asleep at 06:30 = no run), StartWhenAvailable making it fire whenever
# the lid next opened, and task history logging disabled so none of it showed.
#
# RUN AS ROOT on the target server, from a checkout of this repo:
#     sudo bash deploy/install-pipeline-timer.sh
#
# WHAT IT ASSUMES
#   · Python 3.12+ and the venv module
#   · outbound 5432 to BOTH RDS instances (ap-south-1 and ap-south-2) and to
#     the ananya_data host — check with check_connectivity below BEFORE relying
#     on the timer
#   · a .env in the repo root (NOT created here; it holds credentials)
#
# WHERE TO PUT IT
#   Anywhere always-on that can reach the databases. Running inside AWS in
#   ap-south is strongly preferable: the five reports that failed the last
#   laptop run — aum_status, aum_loans, collection_loans, trend_monthly,
#   trend_full — all died with "SSL connection has been closed unexpectedly",
#   which is a long scan over a slow link, not a query defect.
# =============================================================================
set -euo pipefail

APP_USER="${APP_USER:-ananya}"
APP_DIR="${APP_DIR:-/opt/ananya_mis}"
LOG_DIR="${LOG_DIR:-/var/log/ananya_mis}"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

[[ $EUID -eq 0 ]] || { echo "run as root (sudo bash $0)"; exit 1; }

say "service account"
id -u "$APP_USER" &>/dev/null || useradd --system --create-home --shell /usr/sbin/nologin "$APP_USER"

say "application directory"
mkdir -p "$APP_DIR" "$LOG_DIR"
# Copy the repo but never the local virtualenv or logs.
rsync -a --delete \
  --exclude '.git' --exclude '.venv' --exclude 'logs' --exclude 'node_modules' \
  --exclude 'frontend/dist' --exclude 'reports.db' \
  "$SRC_DIR/" "$APP_DIR/"

if [[ ! -f "$APP_DIR/.env" ]]; then
  cat <<'MSG'

  !! No .env in the application directory.
     It holds database credentials and is deliberately NOT generated by this
     script. Copy it across yourself and lock it down:

         install -o ananya -g ananya -m 600 /path/to/.env /opt/ananya_mis/.env

     The timer will fail every night until this exists.

MSG
fi

say "virtualenv"
python3 -m venv "$APP_DIR/.venv"
"$APP_DIR/.venv/bin/pip" install --upgrade pip >/dev/null
"$APP_DIR/.venv/bin/pip" install -r "$APP_DIR/requirements.txt"

say "ownership"
chown -R "$APP_USER:$APP_USER" "$APP_DIR" "$LOG_DIR"
[[ -f "$APP_DIR/.env" ]] && chmod 600 "$APP_DIR/.env"

say "log rotation"
# The pipeline log grows without bound otherwise — the laptop's is already 12 MB.
cat > /etc/logrotate.d/ananya-mis <<EOF
$LOG_DIR/*.log {
    daily
    rotate 30
    compress
    missingok
    notifempty
    copytruncate
    su $APP_USER $APP_USER
}
EOF

say "systemd units"
sed -e "s#/opt/ananya_mis#$APP_DIR#g" \
    -e "s#/var/log/ananya_mis#$LOG_DIR#g" \
    -e "s#^User=.*#User=$APP_USER#" -e "s#^Group=.*#Group=$APP_USER#" \
    "$SRC_DIR/deploy/systemd/ananya-pipeline.service" > /etc/systemd/system/ananya-pipeline.service
cp "$SRC_DIR/deploy/systemd/ananya-pipeline.timer" /etc/systemd/system/ananya-pipeline.timer
systemctl daemon-reload
systemctl enable --now ananya-pipeline.timer

say "installed"
systemctl list-timers ananya-pipeline.timer --no-pager || true
cat <<EOF

Next:
  connectivity   sudo -u $APP_USER $APP_DIR/.venv/bin/python -c \\
                     "import sys; sys.path.insert(0,'$APP_DIR/pipeline'); \\
                      from db import run_query; print(run_query('select 1 ok'))"
  run once now   sudo systemctl start ananya-pipeline.service
  watch it       sudo journalctl -u ananya-pipeline -f
  the log        tail -f $LOG_DIR/pipeline.log
  next fire      systemctl list-timers ananya-pipeline.timer

  A run is FAILED if any single report failed — daily_run exits non-zero on
  purpose, so check with:  systemctl status ananya-pipeline.service

EOF
